---
apiVersion: v1
kind: ReplicationController
metadata:
  name: onlinebookstore
spec:
  replicas: 2
  selector:
    app: onlinebookstore
  template:
    metadata:
      labels:
        app: onlinebookstore
    spec:
      containers:
      - image: raja6522/onlinebookstore
        name: onlinebookstore
        ports:
        - containerPort: 8080        
---
apiVersion: v1
kind: Service
metadata:
  name: onlinebookstore
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: onlinebookstore
 
---
kind: ConfigMap 
apiVersion: v1 
metadata:
  name: mysql-configmap 
data:
  password: root
  
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: onlinebookstore-mysql
  labels:
    app: onlinebookstore
spec:
  replicas: 2
  selector:
    app: onlinebookstore
  template:
    metadata:
      labels:
        app: onlinebookstore
    spec:
      containers:
        - image: mysql
          imagePullPolicy: Always
          name: mysql
          env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
               configMapKeyRef:
                  name: mysql-configmap
                  key: password
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        hostPath:
          path: /tmp/mysqlbackup
---
apiVersion: v1
kind: Service
metadata:
  name: onlinebookstore-mysql
  labels:
    app: onlinebookstore
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: onlinebookstore
